from __future__ import annotations

from environment_agent.schemas import (
    ArtifactPlanItem,
    DependencyMutation,
    EnvironmentConstraint,
    ExternalEvent,
    HistoricalTasks,
    TaskOpportunity,
)


def _artifact_id_by_role(
    artifact_plan: list[ArtifactPlanItem],
    role: str,
) -> str | None:
    return next((item.artifact_id for item in artifact_plan if item.role == role), None)


def generate_task_opportunities(
    event: ExternalEvent,
    artifact_plan: list[ArtifactPlanItem],
    dependency_mutations: list[DependencyMutation],
    constraints: list[EnvironmentConstraint],
    historical_tasks: HistoricalTasks,
) -> list[TaskOpportunity]:
    _ = (dependency_mutations, constraints, historical_tasks)
    artifact_ids = {item.artifact_id for item in artifact_plan}
    incident_required_ids = [
        artifact_id
        for artifact_id in [
            _artifact_id_by_role(artifact_plan, "customer_complaint"),
            _artifact_id_by_role(artifact_plan, "supplier_delay_notice"),
            _artifact_id_by_role(artifact_plan, "exception_shipment_table"),
            _artifact_id_by_role(artifact_plan, "latest_sla_policy"),
            _artifact_id_by_role(artifact_plan, "revised_weekly_report"),
            _artifact_id_by_role(artifact_plan, "customer_response_draft"),
        ]
        if artifact_id is not None
    ]

    if event.event_type == "incident" and len(incident_required_ids) == 6:
        return [
            TaskOpportunity(
                opportunity_id=f"opp_{event.event_id}_update_report_response",
                source_event_id=event.event_id,
                task_type="artifact_update_with_stale_context",
                instruction=(
                    "Use the customer complaint, supplier delay notice, April exception shipment sheet, "
                    "and latest April SLA policy to update the revised weekly operations report and draft "
                    "a customer response. Do not use the stale Q1 SLA policy as the current rule."
                ),
                required_artifact_ids=incident_required_ids,
                capability_tags=[
                    "retrieval",
                    "cross_file_reasoning",
                    "version_selection",
                    "temporal_reasoning",
                    "artifact_update",
                    "customer_communication",
                ],
                validation_hints=[
                    "The answer should mention 17 delayed shipments.",
                    "The report update should cite April exception shipment data.",
                    "The customer response should acknowledge the 17:00 deadline.",
                    "The latest SLA policy should be April SLA update.",
                ],
                negative_rubric_hints=[
                    "Fails if it uses Q1 SLA as the current policy.",
                    "Fails if it ignores customer complaint deadline.",
                    "Fails if it updates unrelated files outside the WorkUnit.",
                ],
            )
        ]

    task_type_by_event = {
        "policy_change": "stale_policy_detection",
        "collaboration": "multi_actor_synthesis",
        "resource_constraint": "plan_adjustment_under_constraints",
        "deadline": "deadline_driven_update",
        "feedback": "feedback_integration",
        "discovery": "information_update",
        "drift": "long_term_context_revision",
    }
    if event.event_type in task_type_by_event:
        required_ids = sorted(artifact_ids)
        return [
            TaskOpportunity(
                opportunity_id=f"opp_{event.event_id}_{task_type_by_event[event.event_type]}",
                source_event_id=event.event_id,
                task_type=task_type_by_event[event.event_type],
                instruction=(
                    f"Use the artifacts generated by the {event.event_type} event to update the relevant "
                    "workspace plan, preserve dependency evidence, and avoid stale or unsupported claims."
                ),
                required_artifact_ids=required_ids,
                capability_tags=[
                    "retrieval",
                    "dependency_reasoning",
                    event.event_type,
                    "artifact_update",
                ],
                validation_hints=[
                    f"The output should explicitly reflect the {event.event_type} trigger.",
                    "The output should use the source and analysis artifacts before the action plan.",
                    "The output should preserve affected entities from the event.",
                ],
                negative_rubric_hints=[
                    f"Fails if it ignores the {event.event_type} event.",
                    "Fails if it updates an action plan without citing dependency evidence.",
                ],
            )
        ]

    return [
        TaskOpportunity(
            opportunity_id=f"opp_{event.event_id}_policy_check",
            source_event_id=event.event_id,
            task_type="stale_policy_detection",
            instruction="Identify the latest policy artifact and explain which older policy artifact is stale.",
            required_artifact_ids=sorted(artifact_ids),
            capability_tags=["retrieval", "version_selection", "rule_following"],
            validation_hints=["The latest policy must be selected according to dependency relation supersedes."],
            negative_rubric_hints=["Fails if stale policy is treated as current."],
        )
    ]
